# Generated by Django 2.2.1 on 2019-05-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('party_number', models.IntegerField(default=1)),
                ('image_file', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
